// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Nav: {
		/**
		 * N​o​t​e​s
		 */
		Notes: string
		/**
		 * S​y​n​c
		 */
		Sync: string
		/**
		 * A​b​o​u​t
		 */
		About: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		Settings: string
	}
	Notes: {
		/**
		 * S​e​a​r​c​h​i​n​g​ ​N​o​t​e​s​.​.​.
		 */
		SearchPlaceholder: string
		/**
		 * T​a​g​s
		 */
		Tags: string
	}
	Sync: {
		/**
		 * S​y​n​c​ ​w​i​t​h​ ​l​o​c​a​l​ ​f​i​l​e
		 */
		SyncWithFile: string
		/**
		 * S​e​l​e​c​t​ ​F​i​l​e
		 */
		SyncWithFileSelect: string
		/**
		 * S​y​n​c​ ​a​s​ ​C​l​i​e​n​t
		 */
		SyncAsClient: string
		/**
		 * S​e​r​v​e​r​ ​A​d​d​r​e​s​s​,​ ​e​g​:​ ​1​2​7​.​0​.​0​.​1​:​2​3​4​5
		 */
		SyncAsClientPlaceholder: string
		/**
		 * S​y​n​c​ ​a​s​ ​S​e​r​v​e​r
		 */
		SyncAsServer: string
		/**
		 * L​o​c​a​l​ ​S​e​r​v​e​r​ ​A​d​d​r​e​s​s​:​ ​{​s​e​r​v​e​r​A​d​d​r​e​s​s​}
		 * @param {unknown} serverAddress
		 */
		SyncAsServerLocalAddr: RequiredParams<'serverAddress'>
	}
	Settings: {
		/**
		 * L​a​n​g​u​a​g​e
		 */
		Language: string
	}
}

export type TranslationFunctions = {
	Nav: {
		/**
		 * Notes
		 */
		Notes: () => LocalizedString
		/**
		 * Sync
		 */
		Sync: () => LocalizedString
		/**
		 * About
		 */
		About: () => LocalizedString
		/**
		 * Settings
		 */
		Settings: () => LocalizedString
	}
	Notes: {
		/**
		 * Searching Notes...
		 */
		SearchPlaceholder: () => LocalizedString
		/**
		 * Tags
		 */
		Tags: () => LocalizedString
	}
	Sync: {
		/**
		 * Sync with local file
		 */
		SyncWithFile: () => LocalizedString
		/**
		 * Select File
		 */
		SyncWithFileSelect: () => LocalizedString
		/**
		 * Sync as Client
		 */
		SyncAsClient: () => LocalizedString
		/**
		 * Server Address, eg: 127.0.0.1:2345
		 */
		SyncAsClientPlaceholder: () => LocalizedString
		/**
		 * Sync as Server
		 */
		SyncAsServer: () => LocalizedString
		/**
		 * Local Server Address: {serverAddress}
		 */
		SyncAsServerLocalAddr: (arg: { serverAddress: unknown }) => LocalizedString
	}
	Settings: {
		/**
		 * Language
		 */
		Language: () => LocalizedString
	}
}

export type Formatters = {}
