stages:
  - format-lint-check
  - build-localnative-core
  - build-localnative-cli
  - build-localnative-iced


image: "rust:latest"

before_script:
    - echo "Add the rustfmt and clippy:"
    - rustup component add rustfmt
    - rustup component add clippy
    - echo "have a try"

format-lint-check :
  stage: format-lint-check
  script:
    - echo "Check the rust and cargo version:"
    - rustc --version && cargo --version
    - echo "Check formt"
    - cd localnative-rs && cargo fmt-check
    - echo "Check code lint"
    - cargo lint

build-localnative-core:
  stage: build-localnative-core
  script:
    - echo "Build localnative core"
    - cd localnative-rs/localnative_core && cargo build

build-localnative-iced:
  stage: build-localnative-iced
  script:
    - echo "Build localnative iced"
    - cd localnative-rs/localnative_iced && cargo build

build-localnative-cli:
  stage: build-localnative-cli
  script:
    - echo "Build localnative cli"
    - cd localnative-rs/localnative_cli && cargo build

  only:
    - branches
    - tags
    - merge_requests
