stages:
  - format-lint-check 


image: "rust:latest"

before_script:
    - echo "Add the rustfmt and clippy:"
    - rustup component add rustfmt
    - rustup component add clippy
    - echo "have a try"

build-code-job:
  stage: format-lint-check 
  script:
    - echo "Check the rust and cargo version:"
    - rustc --version && cargo --version
    - echo "Check formt"
    - cd localnative-rs && cargo fmt-check
    - echo "Check code lint"
    - cargo olint
    - cargo wlint
  only:
    - branches
    - tags
    - merge_requests
