stages:
  - build

image: "rust:latest"

build-code-job:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - echo "Check the rust and cargo version:"
    - rustc --version && cargo --version
    - cd localnative-rs && cargo build