stages:
  - build

image: "rust:latest"

build-code-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  script:
    - echo "Check the rust and cargo version:"
    - rustc --version && cargo --version
    - cd localnative-rs && cargo build