import 'package:intl/intl.dart';

/// Extension methods for Note (will be generated by flutter_rust_bridge)
/// These provide convenience methods for working with notes in the UI

class NoteHelper {
  /// Parse the created_at timestamp into a DateTime
  static DateTime parseCreatedAt(String createdAt) {
    // Format: "YYYY-MM-DD HH:MM:SS:nnnnnnnnn UTC"
    try {
      final parts = createdAt.split(' ');
      if (parts.length >= 2) {
        final datePart = parts[0];
        final timePart = parts[1].split(':');
        if (timePart.length >= 3) {
          final dateTime = '$datePart ${timePart[0]}:${timePart[1]}:${timePart[2]}';
          return DateTime.parse(dateTime);
        }
      }
      return DateTime.now();
    } catch (e) {
      return DateTime.now();
    }
  }

  /// Format the created_at timestamp for display
  static String formatCreatedAt(String createdAt) {
    final dt = parseCreatedAt(createdAt);
    final formatter = DateFormat('MMM d, yyyy h:mm a');
    return formatter.format(dt);
  }

  /// Get list of tags from comma-separated string
  static List<String> parseTags(String tags) {
    if (tags.isEmpty) return [];
    return tags.split(',').map((t) => t.trim()).where((t) => t.isNotEmpty).toList();
  }

  /// Check if annotations (image data) exists
  static bool hasAnnotations(String annotations) {
    return annotations.isNotEmpty;
  }

  /// Validate URL format
  static bool isValidUrl(String url) {
    if (url.isEmpty) return true; // Empty URL is acceptable
    try {
      final uri = Uri.parse(url);
      return uri.hasScheme && (uri.scheme == 'http' || uri.scheme == 'https');
    } catch (e) {
      return false;
    }
  }
}
