//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub value: String,
    pub created_at: ChronoDateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notes_comments::Entity")]
    NotesComments,
}

impl Related<super::notes_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotesComments.def()
    }
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        super::notes_comments::Relation::Notes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::notes_comments::Relation::Comments.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
