//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub url: String,
    pub description: String,
    pub tags: Tags,
    pub created_at: ChronoDateTimeUtc,
    pub is_public: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Tags(pub Vec<String>);

impl std::convert::From<String> for Tags {
    fn from(source: String) -> Self {
        Tags(source.split(",").map(|s| s.to_owned()).collect())
    }
}

impl std::convert::Into<Tags> for Vec<String> {
    fn into(self) -> Tags {
        Tags(self)
    }
}

impl std::convert::From<Tags> for Value {
    fn from(source: Tags) -> Self {
        source.0.join(",").into()
    }
}

impl sea_orm::TryGetable for Tags {
    fn try_get_by<I: sea_orm::ColIdx>(
        res: &QueryResult,
        idx: I,
    ) -> Result<Self, sea_orm::TryGetError> {
        <String as sea_orm::TryGetable>::try_get_by(res, idx)
            .map(|v| Tags(v.split(",").map(|s| s.to_owned()).collect()))
    }
}
impl sea_orm::sea_query::ValueType for Tags {
    fn try_from(v: Value) -> Result<Self, sea_orm::sea_query::ValueTypeErr> {
        <String as sea_orm::sea_query::ValueType>::try_from(v)
            .map(|v| Tags(v.split(",").map(|s| s.to_owned()).collect()))
    }
    fn type_name() -> String {
        stringify!(Tags).to_owned()
    }
    fn array_type() -> sea_orm::sea_query::ArrayType {
        std::convert::Into::<sea_orm::sea_query::ArrayType>::into(
            <String as sea_orm::sea_query::ValueType>::array_type(),
        )
    }
    fn column_type() -> sea_orm::sea_query::ColumnType {
        std::convert::Into::<sea_orm::sea_query::ColumnType>::into(
            <String as sea_orm::sea_query::ValueType>::column_type(),
        )
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notes_comments::Entity")]
    NotesComments,
}

impl Related<super::notes_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotesComments.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        super::notes_comments::Relation::Comments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::notes_comments::Relation::Notes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
