//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notes_comments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub note_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub comment_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comments::Entity",
        from = "Column::CommentId",
        to = "super::comments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Comments,
    #[sea_orm(
        belongs_to = "super::notes::Entity",
        from = "Column::NoteId",
        to = "super::notes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Notes,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
