#!/bin/bash

set -e

cd `dirname $0`/..

script/set-version $1
echo "release web-ext-host version" $1


cd localnative-rs/localnative_cli
cargo build --release

cd ../..

DIR="../localnative-release/v$1/web-ext-host"
mkdir -p $DIR

FILE="localnative-web-ext-host-$1-gnu-linux"
cp localnative-rs/localnative_cli/target/release/localnative-web-ext-host $DIR/$FILE
cd $DIR
sha256sum $FILE > $FILE.sha256
md5sum $FILE > $FILE.md5

rm ../../../localnative/localnative-neon/lib/localnative-web-ext-host*
cp $FILE ../../../localnative/localnative-neon/lib
