#!/bin/bash

set -e

cd `dirname $0`/..

script/set-version $1
echo "release web-ext-host version" $1


cd localnative-rs/localnative_cli
cargo build --release

cd ../..

DIR="../localnative-release/v$1/web-ext-host"
mkdir -p $DIR

cp localnative-rs/localnative_cli/target/release/localnative-web-ext-host $DIR/localnative-web-ext-host-$1
cd $DIR
sha256sum localnative-web-ext-host-$1 > localnative-web-ext-host-$1.sha256
md5sum localnative-web-ext-host-$1 > localnative-web-ext-host-$1.md5

