#!/bin/bash

set -e

cd `dirname $0`/..

echo "set version to" $1


# rs
sed -i "6s/.*/version = \"$1\"/" localnative-rs/localnative_core/Cargo.toml

sed -i "6s/.*/version = \"$1\"/" localnative-rs/localnative_ssb/Cargo.toml

sed -i "5s/.*/version = \"$1\"/" localnative-rs/localnative_cli/Cargo.toml

sed -i "33s/.*/        \"$1\"/" localnative-rs/localnative_ssb/src/lib.rs

# electron
sed -i "3s/.*/  \"version\": \"$1\",/" localnative-electron/package.json
sed -i "18s/.*/const version = \"$1\"/" localnative-electron/src/main.js

# neon
sed -i "3s/.*/  \"version\": \"$1\",/" localnative-neon/package.json
sed -i "18s/.*/let version = '$1'/" localnative-neon/lib/index.js
sed -i "3s/.*/version = \"$1\"/" localnative-neon/native/Cargo.toml
sed -i "20s/.*/version = \"$1\"/" localnative-neon/native/Cargo.toml
sed -i "24s/.*/version = \"$1\"/" localnative-neon/native/Cargo.toml

# web-ext
sed -i "60s/.*/v$1/" localnative-browser-extension/app/popup.html
sed -i "3s/.*/  \"version\": \"$1\",/" localnative-browser-extension/app/manifest.json

# nodejs
sed -i "3s/.*/  \"version\": \"$1\",/" localnative-nodejs/package.json
