#!/bin/bash

set -e

cd `dirname $0`/..

echo "set version to" $1


# rs
gsed -i "6s/.*/version = \"$1\"/" localnative-rs/localnative_core/Cargo.toml
gsed -i "5s/.*/version = \"$1\"/" localnative-rs/localnative_cli/Cargo.toml

# web-ext
gsed -i "60s/.*/v$1/" localnative-browser-extension/app/popup.html
gsed -i "3s/.*/  \"version\": \"$1\",/" localnative-browser-extension/app/manifest.json
