/// Database service wrapping Rust FFI bridge
///
/// This service provides a clean interface to the Rust core database operations.
/// The actual bridge functions are generated by flutter_rust_bridge_codegen.
///
/// To generate the bridge code, run:
/// ```
/// flutter_rust_bridge_codegen
/// ```

// Import will be available after running flutter_rust_bridge_codegen
// import '../bridge_generated.dart';

class DatabaseService {
  // Singleton pattern
  static final DatabaseService _instance = DatabaseService._internal();
  factory DatabaseService() => _instance;
  DatabaseService._internal();

  // Note: The bridge functions will be imported from bridge_generated.dart
  // after running flutter_rust_bridge_codegen. The methods below show
  // the interface that will be used.

  /// Select notes with pagination
  ///
  /// Returns a NotesResponse containing notes, count, days, and tags.
  Future<dynamic> selectNotes({required int limit, required int offset}) async {
    // Will call: return await selectNotes(limit: limit, offset: offset);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Search notes by query string
  ///
  /// Searches across title, URL, tags, and description.
  Future<dynamic> searchNotes({
    required String query,
    required int limit,
    required int offset,
  }) async {
    // Will call: return await searchNotes(query: query, limit: limit, offset: offset);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Insert a new note
  ///
  /// Returns updated notes list after insertion.
  Future<dynamic> insertNote({
    required String title,
    required String url,
    required String tags,
    required String description,
    String comments = '',
    String annotations = '',
    bool isPublic = false,
    required int limit,
    required int offset,
  }) async {
    // Will call: return await insertNote(...)
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Delete a note by rowid
  ///
  /// Returns updated notes list after deletion.
  Future<dynamic> deleteNote({
    required int rowid,
    required int limit,
    required int offset,
  }) async {
    // Will call: return await deleteNote(rowid: rowid, limit: limit, offset: offset);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Filter notes by date range and optional query
  ///
  /// Returns notes within the specified date range.
  Future<dynamic> filterNotes({
    required String query,
    required String from,
    required String to,
    required int limit,
    required int offset,
  }) async {
    // Will call: return await filterNotes(...)
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Start RPC server for syncing
  ///
  /// Starts server on specified address (e.g., "0.0.0.0:2345")
  Future<String> startServer({required String addr}) async {
    // Will call: return await startServer(addr: addr);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Sync with remote RPC server
  ///
  /// Connects to server and syncs notes bidirectionally.
  Future<String> syncWithServer({required String addr}) async {
    // Will call: return await syncWithServer(addr: addr);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Stop remote RPC server
  Future<String> stopServer({required String addr}) async {
    // Will call: return await stopServer(addr: addr);
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Sync via SQLite database file attachment
  ///
  /// Directly syncs with another database file.
  Future<dynamic> syncViaAttach({
    required String dbPath,
    required int limit,
    required int offset,
  }) async {
    // Will call: return await syncViaAttach(...)
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }

  /// Initialize the database service
  Future<void> init() async {
    // Will call: await initApp();
    throw UnimplementedError('Run flutter_rust_bridge_codegen to generate bridge code');
  }
}
