# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'localnative-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for localnative-ios

  target 'localnative-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'localnative-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'share-ext' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for share-ext

end
