# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

pod 'MMWormhole', '~> 2.0.0'

target 'localnative-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MMWormhole', '~> 2.0.0'

  # Pods for localnative-ios

  target 'localnative-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'localnative-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'share-ext' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MMWormhole', '~> 2.0.0'
  pod 'UITextView+Placeholder'
  # Pods for share-ext

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
